const colors = require('tailwindcss/colors')

module.exports = {
  mode: 'jit',
  content: ['./src/**/*.{html,js}'],
  purge: ["./**/*.html"]
,
  theme: {
    extend: {
      fontFamily: {
        sans:"'cairo'",
        Poppins: "'Poppins', sans-serif",
        Quicksand: "'Quicksand', sans-serif",
      },
      colors: {
        'color-header': '#60b4df',
        'color-overlay': 'rgb(56, 165, 238, 0.5)',
        'text-primary': '#69bde7',
        'color-grey': '#9194A2',
        'color-main-one': '#f0f1ef',
        'color-main-two': '#4964a1',
        'color-main-three': '#7eb57a',
        'color-main-four': '#7b49d2',
        'color-main-five': '#7b57f6',
        'color-main-six': ' #f9f9fa',
        'color-main-seven': '#b9dObd',
        'color-main-eight': ' #5e4978',
        'color-main-nine': ' #7ab378',
        'bookmark-white': '#f7f7f7',
        'border-color':'#e6ecf5',
        'default-primary':'#7774e7',
        'default-success':'#37c936',
        'default-text-color':'#72777a',
        'default-warning':'#fc0',
        'default-white':'#fff',
        'sellar-primary': '#7b57f6',
        'windows-green':'#7ab378',
        'light': 'var(--light)',
        'dark': 'var(--dark)',
        'darker': 'var(--darker)',
        'primary': {
          'DEFAULT': 'var(--color-primary)',
          '50': 'var(--color-primary-50)',
          '100': 'var(--color-primary-100)',
          'light': 'var(--color-primary-light)',
          'lighter': 'var(--color-primary-lighter)',
          'dark': 'var(--color-primary-dark)',
          'darker': 'var(--color-primary-darker)',
        },
        'secondary': {
          'DEFAULT': colors.fuchsia[600],
          '50': colors.fuchsia[50],
          '100': colors.fuchsia[100],
          'light': colors.fuchsia[500],
          'lighter': colors.fuchsia[400],
          'dark': colors.fuchsia[700],
          'darker': colors.fuchsia[800],
        },
        'success': {
          'DEFAULT': colors.green[600],
          '50': colors.green[50],
          '100': colors.green[100],
          'light': colors.green[500],
          'lighter': colors.green[400],
          'dark': colors.green[700],
          'darker': colors.green[800],
        },
        'warning': {
          'DEFAULT': colors.orange[600],
          '50': colors.orange[50],
          '100': colors.orange[100],
          'light': colors.orange[500],
          'lighter': colors.orange[400],
          'dark': colors.orange[700],
          'darker': colors.orange[800],
        },
        'danger': {
          'DEFAULT': colors.red[600],
          '50': colors.red[50],
          '100': colors.red[100],
          'light': colors.red[500],
          'lighter': colors.red[400],
          'dark': colors.red[700],
          'darker': colors.red[800],
        },
        'info': {
          'DEFAULT': colors.cyan[600],
          '50': colors.cyan[50],
          '100': colors.cyan[100],
          'light': colors.cyan[500],
          'lighter': colors.cyan[400],
          'dark': colors.cyan[700],
          'darker': colors.cyan[800],
        },
      },
    },
  },
  plugins: [],
}
